# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/search-forecast',
                'doc_host': 'https://redam94.github.io',
                'git_url': 'https://github.com/redam94/search-forecast',
                'lib_path': 'search_forecast'},
  'syms': {'search_forecast.core': {'search_forecast.core.foo': ('core.html#foo', 'search_forecast/core.py')}}}
